package com.dreamykids.bedtimestories.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import com.dreamykids.bedtimestories.model.*
import com.dreamykids.bedtimestories.ui.components.*
import com.dreamykids.bedtimestories.viewmodel.DreamyViewModel

@Composable fun HomeScreen(vm:DreamyViewModel,onCategory:(String)->Unit,onSettings:()->Unit){ val q by vm.query.collectAsState(); val results by vm.searchResults.collectAsState(); NightSky{ LazyVerticalGrid(GridCells.Adaptive(170.dp),contentPadding=PaddingValues(bottom=100.dp)){ item(span={GridItemSpan(maxLineSpan)}){HeroHeader(onSettings)}; item(span={GridItemSpan(maxLineSpan)}){MoonHero()}; item(span={GridItemSpan(maxLineSpan)}){ OutlinedTextField(value=q,onValueChange=vm::updateQuery,modifier=Modifier.fillMaxWidth().padding(20.dp),leadingIcon={Icon(Icons.Rounded.Search,"Search")},label={Text("Search stories, categories, keywords, narrators")},singleLine=true) }; if(q.isBlank()) items(vm.categories){ CategoryCard(it){onCategory(it.id)} } else items(results, span={GridItemSpan(maxLineSpan)}){ StoryCard(it,false,{vm.toggleFavorite(it.id)},{vm.play(it)}) } } } }
@Composable fun CategoryScreen(vm:DreamyViewModel,id:String,onStory:(String)->Unit){ val fav by vm.favorites.collectAsState(); val cat=vm.categories.first{it.id==id}; NightSky{ LazyColumn(contentPadding=PaddingValues(vertical=20.dp)){ item{ Text("${cat.emoji} ${cat.title} Stories",fontSize=30.sp,fontWeight=FontWeight.ExtraBold,modifier=Modifier.padding(20.dp)); Text(cat.description,modifier=Modifier.padding(horizontal=20.dp),color=MaterialTheme.colorScheme.onSurface.copy(.75f))}; items(vm.storiesFor(id)){ StoryCard(it,it.id in fav,{vm.toggleFavorite(it.id)},{vm.play(it); onStory(it.id)}) } } } }
@Composable fun PlayerScreen(vm:DreamyViewModel){ val p by vm.player.collectAsState(); NightSky{ Column(Modifier.fillMaxSize().padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.SpaceAround){ Text(p.current?.emoji ?: "📚",fontSize=130.sp); Text(p.current?.title ?: "Choose a story",fontSize=28.sp,fontWeight=FontWeight.ExtraBold); Text("Narrated by ${p.current?.narrator ?: "Dreamy Kids"} • ${p.current?.durationMinutes ?: 0} minutes"); LinearProgressIndicator(progress={p.progress},modifier=Modifier.fillMaxWidth().height(10.dp)); Row(verticalAlignment=Alignment.CenterVertically){ IconButton({}){Icon(Icons.Rounded.SkipPrevious,"Previous")}; IconButton({}){Icon(Icons.Rounded.Replay10,"15 sec rewind")}; FilledIconButton({vm.togglePlay()},Modifier.size(76.dp)){Icon(if(p.isPlaying) Icons.Rounded.Pause else Icons.Rounded.PlayArrow,"Play",Modifier.size(42.dp))}; IconButton({}){Icon(Icons.Rounded.Forward10,"15 sec forward")}; IconButton({}){Icon(Icons.Rounded.SkipNext,"Next")} }; Row{ AssistChip({},{Text("❤ Favorite")}); Spacer(Modifier.width(8.dp)); AssistChip({},{Text("${p.speed}x Speed")}); Spacer(Modifier.width(8.dp)); AssistChip({},{Text("Sleep Timer")}) }; TimerChips(p.sleepTimerMinutes){vm.setTimer(it)} } } }
@Composable fun FavoritesScreen(vm:DreamyViewModel,onStory:(String)->Unit){ val fav by vm.favorites.collectAsState(); NightSky{ LazyColumn{ item{Text("❤️ Favorites",fontSize=30.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(20.dp)); Text("Sort by: Recently Played • Favorites • Downloaded",modifier=Modifier.padding(horizontal=20.dp))}; items(vm.categories.flatMap{vm.storiesFor(it.id)}.filter{it.id in fav}){ StoryCard(it,true,{vm.toggleFavorite(it.id)},{vm.play(it);onStory(it.id)}) } } } }
@Composable fun TimerScreen(vm:DreamyViewModel){ val p by vm.player.collectAsState(); NightSky{ Column(Modifier.padding(24.dp)){Text("🕒 Sleep Timer",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Fade volume before stopping playback for a peaceful ending."); TimerChips(p.sleepTimerMinutes){vm.setTimer(it)} } } }
@Composable fun MoreScreen(vm:DreamyViewModel){ val s by vm.settings.collectAsState(); NightSky{ Column(Modifier.padding(24.dp)){Text("⚙ More",fontSize=30.sp,fontWeight=FontWeight.Bold); listOf("Dark mode" to s.darkMode,"Auto play next story" to s.autoPlayNext,"Remember last story" to s.rememberLastStory,"Notifications" to s.notifications).forEach{ Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(it.first,Modifier.weight(1f)); Switch(it.second,{})} }; Text("About • Privacy Policy • Premium ready architecture",modifier=Modifier.padding(top=20.dp)) } } }
